baseURL = 'https://nopitan.com/'
languageCode = 'ja-JP'
title = 'のぴたん係長'
theme = "lynx"
publishDir = "docs"
enableEmoji = true
enableGitInfo = true
googleAnalytics = "G-SWFMH94FY2"

[author]
name = "のぴたん係長"

[params]
attribution = false

[params.author]
name = "のぴたん係長"
headline = "I love FromSoftware."
image = "images/profile.png"
links = [
  { twitter = { href = "https://twitter.com/ChiefNopitan", text = "Twitter (ChiefNopitan)" } },
  { trophy = { href = "https://psnprofiles.com/nopitan", text = "Trophies (nopitan)" } },
  { twitch = { href = "https://www.twitch.tv/nopitan", text = "Twitch (nopitan)" } },
  { niconico = { href = "https://com.nicovideo.jp/community/co3103323", text = "niconico (co3103323)" } },
  { clubdam = { href = "https://www.clubdam.com/app/damtomo/member/info/Profile.do?damtomoId=NzgyMDE5ODk", text = "DAM★とも" } },
  { twitter = { href = "https://twitter.com/EngineerNopitan", text = "Twitter (EngineerNopitan)" } },
  { github = { href = "https://github.com/nopitan", text = "Github (nopitan)" } },
]

[taxonomies]
