name: Hugo
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Switch to `github-pages` branch, and rebase it on top of `origin/main`
        run: git switch -c github-pages
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Run Hugo
        run: hugo
      - name: Copy CNAME
        run: cp CNAME docs/
      - name: Commit docs
        run: |
          git config --local user.name "${{ github.event.pusher.name }}"
          git config --local user.email "${{ github.event.pusher.email }}"
          git add --force docs
          git commit -m "update docs (published by GitHub Pages)"
          git push --force --set-upstream origin github-pages
